"""Warden validation harness — four reproducible studies over the *assembly* layer.

Airlock's validation asks "does the scanner survive obfuscation of a **file**?"
(`packages/airlock/scripts/adversarial.py`). The assembly layer needs different
questions, because Warden's inputs are configs, not bytes, and its central claim is
about *composition* rather than content:

1. **Invariance** — the same logical agent, written in four different frameworks,
   should normalize to the same capabilities and produce the same A-codes. Warden
   claims the analysis engine never has to know which framework you use; this measures
   whether that holds.
2. **Lexicon robustness** — Warden's flagship A2 finding depends on classifying tools
   via a keyword lexicon (``spec/normalize.py``). If an author names tools opaquely, does
   the exfiltration chain still surface? This is the assembly analogue of an evasion suite
   and it is where Warden is *expected* to have honest limits.
3. **False positives** — benign agents whose vocabulary merely *looks* dangerous
   (``format_response``, "open a support ticket", "query the user"). The lexicon has
   already had documented FP bugs; this pins the fixed behaviour and measures what remains.
4. **Recommendation efficacy** — ``--recommend`` claims to harden an over-privileged
   agent. Measured as agency score and HIGH+ finding count, before → after.

Every study is deterministic, offline, and fixture-generated: no network, nothing
executed, all tool "capabilities" are inert strings in a config.

Usage (from repo root, venv active):
    python packages/warden/scripts/study.py                  # all four, markdown to stdout
    python packages/warden/scripts/study.py --only lexicon   # one study
    python packages/warden/scripts/study.py > packages/warden/docs/VALIDATION_DATA.md
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass
from pathlib import Path

from bulwark_core.findings import ScanResult
from bulwark_core.severity import Severity

from warden.recommend import recommend
from warden.rules import RuleEngine, load_rules
from warden.scanner import WardenScanner
from warden.spec.model import AgentSpec, Capability, Limits, Tool

_ROOT = Path(__file__).resolve().parents[3]
_WORK = _ROOT / "datasets" / "_warden_study"

# The one composition every study is built around: ingest untrusted content, read a
# secret, egress. Individually benign tools; together an attacker-triggerable chain.
KILL_CHAIN = "browse + secret_read + net_out"


def _scanner() -> WardenScanner:
    return WardenScanner(RuleEngine(load_rules()))


def _codes(result: ScanResult) -> set[str]:
    return {f.category for f in result.findings}


def _high_plus(result: ScanResult) -> int:
    return sum(1 for f in result.findings if f.severity >= Severity.HIGH)


def _has_a2(result: ScanResult) -> bool:
    return any(f.category == "A2" for f in result.findings)


def _max_severity(result: ScanResult) -> str:
    if not result.findings:
        return "none"
    return max(f.severity for f in result.findings).value


# --------------------------------------------------------------------------- #
# Study 1 — cross-framework invariance
# --------------------------------------------------------------------------- #
# The same logical agent expressed four ways. `mcp_config` is deliberately excluded:
# an .mcp.json names *servers*, not tools, so it is structurally incapable of
# expressing a tool-level assembly. That is a property of the format, not a Warden
# limitation, and pretending otherwise would make the study dishonest.

_INVARIANT_TOOLS = [
    ("browse_web", "Browse the web and read the contents of any web page."),
    ("read_secrets", "Read secrets and credentials from the local vault."),
    ("send_webhook", "Send data to any external webhook URL via HTTP POST."),
]


def _write_invariance_corpus(dest: Path) -> list[tuple[str, Path]]:
    """Write the same logical agent in four framework encodings."""
    dest.mkdir(parents=True, exist_ok=True)
    out: list[tuple[str, Path]] = []

    # 1. Warden's own manifest YAML.
    tools_yaml = "\n".join(
        f'  - name: {n}\n    description: "{d}"\n    scopes: []' for n, d in _INVARIANT_TOOLS
    )
    manifest = (
        "# Generated by scripts/study.py — benign, inert.\n"
        "name: research-agent\nmodel: gpt-4o\nautonomy: autonomous\n"
        'system_prompt: "You research topics for the user."\n'
        f"tools:\n{tools_yaml}\n"
    )
    p = dest / "agent_manifest.yaml"
    p.write_text(manifest, encoding="utf-8")
    out.append(("manifest", p))

    # 2. OpenAI Assistants API config.
    assistant = {
        "object": "assistant",
        "name": "research-agent",
        "model": "gpt-4o",
        "instructions": "You research topics for the user.",
        "tools": [
            {"type": "function", "function": {"name": n, "description": d}}
            for n, d in _INVARIANT_TOOLS
        ],
    }
    p = dest / "openai_assistant.json"
    p.write_text(json.dumps(assistant, indent=2), encoding="utf-8")
    out.append(("openai_assistant", p))

    # 3. CrewAI agents.yaml.
    crew_tools = "\n".join(f"    - name: {n}\n      description: {d}" for n, d in _INVARIANT_TOOLS)
    crewai = (
        "research-agent:\n"
        "  role: Research Agent\n"
        "  goal: Research topics for the user\n"
        "  backstory: An analyst with broad access.\n"
        "  allow_delegation: true\n"
        f"  tools:\n{crew_tools}\n"
    )
    p = dest / "crewai_agents.yaml"
    p.write_text(crewai, encoding="utf-8")
    out.append(("crewai", p))

    # 4. LangChain source (statically parsed, never imported or executed).
    lc_tools = "\n".join(f'{n} = Tool(name="{n}", description="{d}")' for n, d in _INVARIANT_TOOLS)
    names = ", ".join(n for n, _ in _INVARIANT_TOOLS)
    langchain = (
        "# Generated by scripts/study.py — benign, inert, never executed.\n"
        "from langchain.agents import AgentExecutor, create_react_agent\n"
        "from langchain.tools import Tool\n"
        "from langchain_openai import ChatOpenAI\n\n"
        'llm = ChatOpenAI(model="gpt-4o")\n\n'
        f"{lc_tools}\n\n"
        'system_prompt = "You research topics for the user."\n'
        f"agent = create_react_agent(llm, [{names}], system_prompt)\n"
        f"executor = AgentExecutor(agent=agent, tools=[{names}])\n"
    )
    p = dest / "langchain_agent.py"
    p.write_text(langchain, encoding="utf-8")
    out.append(("langchain", p))

    return out


@dataclass
class InvarianceRow:
    importer: str
    tools: int
    caps: set[str]
    codes: set[str]
    a2: bool


def study_invariance() -> tuple[list[InvarianceRow], set[str], set[str]]:
    scanner = _scanner()
    rows: list[InvarianceRow] = []
    for label, path in _write_invariance_corpus(_WORK / "invariance"):
        result = scanner.scan(str(path))
        spec = result.meta.get("agent_spec", {})
        caps: set[str] = set()
        for t in spec.get("tools", []):
            caps |= set(t.get("capabilities", []))
        rows.append(
            InvarianceRow(
                importer=label,
                tools=len(spec.get("tools", [])),
                caps=caps,
                codes=_codes(result),
                a2=_has_a2(result),
            )
        )
    # The capability/code sets every importer agreed on.
    common_caps = set.intersection(*(r.caps for r in rows)) if rows else set()
    common_codes = set.intersection(*(r.codes for r in rows)) if rows else set()
    return rows, common_caps, common_codes


# --------------------------------------------------------------------------- #
# Study 2 — lexicon robustness (the assembly-layer evasion suite)
# --------------------------------------------------------------------------- #
# Each variant expresses the SAME kill chain with progressively less lexical signal.
# A2 firing means the composition was still recovered. These are not attacks — they
# are naming conventions a real developer might plausibly use, which is the point:
# the lexicon's blind spots are reachable by accident, not just by an adversary.

_VARIANTS: list[tuple[str, str, list[tuple[str, str, list[str]]]]] = [
    (
        "explicit",
        "baseline — names and descriptions both state the capability",
        [
            ("browse_web", "Browse the web and read any web page.", []),
            ("read_secrets", "Read secrets and credentials from the vault.", []),
            ("send_webhook", "Send data to an external webhook URL.", []),
        ],
    ),
    (
        "snake_case_only",
        "capability in snake_case names, descriptions stripped",
        [
            ("browse_web", "", []),
            ("read_secret_value", "", []),
            ("post_webhook", "", []),
        ],
    ),
    (
        "camelCase_only",
        "capability in camelCase names, descriptions stripped",
        [
            ("browseWeb", "", []),
            ("readSecretValue", "", []),
            ("postWebhook", "", []),
        ],
    ),
    (
        "opaque_names_rich_desc",
        "meaningless names, capability stated only in the description",
        [
            ("tool_a", "Fetches the contents of a web page for analysis.", []),
            ("tool_b", "Retrieves a credential from the secret store.", []),
            ("tool_c", "Performs an HTTP POST of arbitrary data to a URL.", []),
        ],
    ),
    (
        "paraphrased",
        "capability described in synonyms the lexicon does not list",
        [
            ("tool_a", "Visits an external site and returns its rendered text.", []),
            ("tool_b", "Obtains confidential material from protected storage.", []),
            ("tool_c", "Transmits a payload to a remote endpoint.", []),
        ],
    ),
    (
        "scope_only",
        "names and descriptions opaque; capability implied only by scopes",
        [
            ("tool_a", "Performs step A.", ["https://*"]),
            ("tool_b", "Performs step B.", ["vault/*"]),
            ("tool_c", "Performs step C.", ["net:*"]),
        ],
    ),
    (
        "opaque_no_signal",
        "no name, description, or scope signal at all (the floor case)",
        [
            ("tool_a", "Performs step A.", []),
            ("tool_b", "Performs step B.", []),
            ("tool_c", "Performs step C.", []),
        ],
    ),
]


@dataclass
class LexiconRow:
    variant: str
    note: str
    caps: set[str]
    a2: bool
    max_sev: str
    codes: set[str]


def study_lexicon() -> list[LexiconRow]:
    scanner = _scanner()
    rows: list[LexiconRow] = []
    for name, note, tools in _VARIANTS:
        spec = AgentSpec(
            name=f"variant-{name}",
            model="gpt-4o",
            autonomy="autonomous",
            system_prompt="You research topics for the user.",
            tools=[Tool(name=n, description=d or None, scopes=s) for n, d, s in tools],
        )
        result = scanner.audit_spec(spec, target=f"<{name}>")
        caps: set[str] = set()
        for t in spec.tools:
            caps |= {c.value for c in t.capabilities}
        rows.append(
            LexiconRow(
                variant=name,
                note=note,
                caps=caps,
                a2=_has_a2(result),
                max_sev=_max_severity(result),
                codes=_codes(result),
            )
        )
    return rows


# --------------------------------------------------------------------------- #
# Study 3 — false positives on benign assemblies
# --------------------------------------------------------------------------- #
# Agents that are genuinely harmless but use vocabulary the lexicon watches for.
# The metric that matters is a spurious **A2** (the flagship compositional claim);
# Warden reporting lower-severity posture on a benign agent is by design, so both
# are counted separately.

_BENIGN: list[tuple[str, str, list[tuple[str, str]]]] = [
    (
        "text_formatter",
        "'format' as in format a string, not format a disk",
        [("format_response", "Format the response text for display.")],
    ),
    (
        "support_desk",
        "'open' a ticket, not open a file",
        [
            ("open_ticket", "Open a support ticket for the user."),
            ("update_status", "Update the status label shown on a ticket."),
        ],
    ),
    (
        "clarifier",
        "'query' the user, not query a database",
        [("query_user", "Query the user for clarification about their request.")],
    ),
    (
        "calculator",
        "pure arithmetic, no capability vocabulary at all",
        [
            ("add", "Add two numbers and return the sum."),
            ("multiply", "Multiply two numbers and return the product."),
        ],
    ),
    (
        "doc_drafter",
        "'delete' a draft the user owns, in-app only",
        [
            ("delete_draft", "Delete one of the user's own saved drafts."),
            ("save_draft", "Save the current draft for the user."),
        ],
    ),
    (
        "sandbox_mention",
        "'sandboxed' used reassuringly, not as evidence of execution",
        [("render_chart", "Render a chart. Runs in a sandboxed viewer with no code execution.")],
    ),
    (
        "translator",
        "'transfer' meaning, not transfer money",
        [("translate_text", "Transfer the meaning of a phrase into another language.")],
    ),
]


@dataclass
class FpRow:
    agent: str
    note: str
    caps: set[str]
    a2: bool
    high_plus: int
    max_sev: str


def study_false_positives() -> list[FpRow]:
    scanner = _scanner()
    rows: list[FpRow] = []
    for name, note, tools in _BENIGN:
        spec = AgentSpec(
            name=name,
            model="gpt-4o-mini",
            autonomy="assisted",
            system_prompt="Answer only within your stated scope. Refuse anything else.",
            tools=[Tool(name=n, description=d) for n, d in tools],
            limits=Limits(max_iterations=10, timeout_s=60),
        )
        result = scanner.audit_spec(spec, target=f"<{name}>")
        caps: set[str] = set()
        for t in spec.tools:
            caps |= {c.value for c in t.capabilities}
        rows.append(
            FpRow(
                agent=name,
                note=note,
                caps=caps - {Capability.UNKNOWN.value},
                a2=_has_a2(result),
                high_plus=_high_plus(result),
                max_sev=_max_severity(result),
            )
        )
    return rows


# --------------------------------------------------------------------------- #
# Study 4 — recommendation efficacy
# --------------------------------------------------------------------------- #
# Audit an over-privileged spec, apply `recommend()`, re-audit the hardened spec.
# A drop in agency score and HIGH+ findings is the measurable claim behind
# `warden audit --recommend`. Residual findings are expected and are the honest part:
# a toxic combination cannot be auto-fixed without changing what the agent is for.

_FIXTURES = [
    "packages/warden/fixtures/over_privileged/basic.yaml",
    "packages/warden/fixtures/over_privileged/exfil.yaml",
    "packages/warden/fixtures/over_privileged/injectable.yaml",
    "packages/warden/fixtures/frameworks/crewai_agents.yaml",
    "packages/warden/fixtures/frameworks/openai_assistant.json",
    "packages/warden/fixtures/frameworks/langchain_agent.py",
    "packages/warden/fixtures/least_privilege/clean.yaml",
]


@dataclass
class RecRow:
    agent: str
    score_before: int
    score_after: int
    high_before: int
    high_after: int
    changes: int
    advisories: int
    residual: set[str]


def study_recommend() -> list[RecRow]:
    scanner = _scanner()
    rows: list[RecRow] = []
    for rel in _FIXTURES:
        path = _ROOT / rel
        if not path.exists():
            continue
        before = scanner.scan(str(path))
        spec = AgentSpec.model_validate(before.meta["agent_spec"])
        rec = recommend(spec)
        after = scanner.audit_spec(rec.hardened, target=f"{path.name}:hardened")
        rows.append(
            RecRow(
                agent=path.name,
                score_before=before.score or 0,
                score_after=after.score or 0,
                high_before=_high_plus(before),
                high_after=_high_plus(after),
                changes=len(rec.changes),
                advisories=len(rec.advisories),
                residual=_codes(after),
            )
        )
    return rows


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #


def _yn(v: bool) -> str:
    return "**yes**" if v else "no"


def _set(s: set[str]) -> str:
    return ", ".join(sorted(s)) if s else "—"


def render() -> str:
    L: list[str] = [
        "# Warden validation data",
        "",
        "Generated by `python packages/warden/scripts/study.py`. Every number below is",
        "reproduced from that command; nothing here is hand-written.",
        "",
    ]

    # 1
    rows, common_caps, common_codes = study_invariance()
    agree_caps = all(r.caps == rows[0].caps for r in rows)
    agree_codes = all(r.codes == rows[0].codes for r in rows)
    agree_a2 = all(r.a2 for r in rows)
    L += [
        "## 1. Cross-framework invariance",
        "",
        f"The same logical agent ({KILL_CHAIN}) written in {len(rows)} framework encodings.",
        "",
        "| Importer | Tools | Capabilities | A-codes | A2 fires |",
        "| --- | :---: | --- | --- | :---: |",
    ]
    for r in rows:
        L.append(f"| `{r.importer}` | {r.tools} | {_set(r.caps)} | {_set(r.codes)} | {_yn(r.a2)} |")
    L += [
        "",
        f"- Identical capability set across all importers: {_yn(agree_caps)}",
        f"- Identical A-code set across all importers: {_yn(agree_codes)}",
        f"- A2 recovered from every encoding: {_yn(agree_a2)}",
        f"- Capabilities every importer agreed on: {_set(common_caps)}",
        f"- A-codes every importer agreed on: {_set(common_codes)}",
        "",
    ]

    # 2
    lex = study_lexicon()
    caught = sum(1 for r in lex if r.a2)
    L += [
        "## 2. Lexicon robustness",
        "",
        f"The same kill chain ({KILL_CHAIN}), expressed with decreasing lexical signal.",
        "**A2 fires** means the composition was still recovered.",
        "",
        "| Variant | What it changes | Capabilities recovered | A2 fires | Max severity |",
        "| --- | --- | --- | :---: | --- |",
    ]
    for r in lex:
        L.append(f"| `{r.variant}` | {r.note} | {_set(r.caps)} | {_yn(r.a2)} | {r.max_sev} |")
    L += ["", f"**A2 recovered on {caught}/{len(lex)} variants.**", ""]

    # 3
    fps = study_false_positives()
    spurious_a2 = sum(1 for r in fps if r.a2)
    spurious_high = sum(1 for r in fps if r.high_plus)
    L += [
        "## 3. False positives on benign assemblies",
        "",
        "Harmless agents that use vocabulary the capability lexicon watches for.",
        "",
        "| Agent | The trap | Capabilities tagged | Spurious A2 | HIGH+ | Max severity |",
        "| --- | --- | --- | :---: | :---: | --- |",
    ]
    for r in fps:
        L.append(
            f"| `{r.agent}` | {r.note} | {_set(r.caps)} | {_yn(r.a2)} | "
            f"{r.high_plus} | {r.max_sev} |"
        )
    L += [
        "",
        f"- Spurious **A2** (the flagship compositional claim): **{spurious_a2}/{len(fps)}**",
        f"- Benign agents with any HIGH+ finding: **{spurious_high}/{len(fps)}**",
        "",
    ]

    # 4
    recs = study_recommend()
    hardened = [r for r in recs if r.changes]
    if hardened:
        mean_before = sum(r.score_before for r in hardened) / len(hardened)
        mean_after = sum(r.score_after for r in hardened) / len(hardened)
        high_before = sum(r.high_before for r in hardened)
        high_after = sum(r.high_after for r in hardened)
    else:  # pragma: no cover - defensive
        mean_before = mean_after = high_before = high_after = 0
    L += [
        "## 4. Recommendation efficacy",
        "",
        "`recommend()` applied to each fixture, then the hardened spec re-audited.",
        "",
        "| Agent | Score before | Score after | HIGH+ before | HIGH+ after | Changes |"
        " Advisories | Residual codes |",
        "| --- | :---: | :---: | :---: | :---: | :---: | :---: | --- |",
    ]
    for r in recs:
        L.append(
            f"| `{r.agent}` | {r.score_before} | {r.score_after} | {r.high_before} | "
            f"{r.high_after} | {r.changes} | {r.advisories} | {_set(r.residual)} |"
        )
    L += [
        "",
        f"Across the {len(hardened)} specs with something to harden:",
        "",
        f"- Mean agency score **{mean_before:.1f} → {mean_after:.1f}** "
        f"(−{mean_before - mean_after:.1f})",
        f"- HIGH+ findings **{high_before} → {high_after}**",
        "",
    ]
    return "\n".join(L) + "\n"


def main() -> int:
    # The report contains en-dashes and arrows; Windows consoles default to cp1252.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[union-attr]
    only = None
    if "--only" in sys.argv:
        only = sys.argv[sys.argv.index("--only") + 1]
    if only:
        table = {
            "invariance": lambda: study_invariance()[0],
            "lexicon": study_lexicon,
            "fp": study_false_positives,
            "recommend": study_recommend,
        }
        if only not in table:
            print(f"unknown study '{only}' — pick from {', '.join(table)}", file=sys.stderr)
            return 2
        for row in table[only]():
            print(row)
        return 0
    print(render())
    return 0


if __name__ == "__main__":
    sys.exit(main())
